### ISSUE TITLE
[FUSION/LDV] No output after clean run

### ISSUE THREAD

**Issue by spono** [biglimp/qgis-fusion#5]
after testing some tools (_CanopyModel_, _GroundFilter_, _GridMetrics_, etc), it seems that none of them return an output.
I checked the available logs and they appear a bit misleading:

1. the one in the tool's window shows a quite complete cmd line, but I don't understand why OUTPUT it is shown as a separate one (that could also be the reason why the run doesn't end well)

![canmodel](https://user-images.githubusercontent.com/14940295/96108024-69c4d280-0edd-11eb-8e67-3d111c320931.png)

2. the one in the "History" log, shows this pretty messy result:
`processing.run("fusion:canopymodel", {'INPUT':'D:\\test\\Bourra\\2011\\LAS\\_\\bourra_tot.laz','CELLSIZE':10,'XYUNITS':0,'ZUNITS':0,'OUTPUT_DTM':'C:/Users/spono/Desktop/chm_10m.dtm','GROUND':'','MEDIAN':'','SMOOTH':'','CLASS':'','SLOPE':False,'ASCII':True,'ADVANCED_MODIFIERS':''})`

I tried to run the line reported at bullet 1 directly from the CMD line and it works fine, so it seems t be an issue related to the correct call to the _exe_ file.
Do you have any idea where the problem may lie?

**Comment by biglimp** [comment]
I tried and could not reproduce your issue. I am producing output files.
1. The reason why output is separated is just how the processing interface is designed. FUSION tools works since the output is generated by the fusion commands. Could there be an issue with your paths or maybe that the laz files is not loaded correctly. However, if you got an FUSION error that should have popped up in the log-window.
2. The log looks ok to me. The double \\ is there since windows use backslash instead of forwardslash and therefore two of them is requried.

**Comment by spono** [comment]
solved...removed the plugin and reinstalled and now it works.
